\mainmatter 

# Ecuaciones diferenciales de primer orden y primer grado
\begin{align*}
  5&=6\\
  &=7
\end{align*}
Una ecuación ordinaria de primer orden y primer grado se representa como $$F\left(x,y,\frac{dy}{dx}\right)=0$$ donde $F$ relaciona tres variables; una funcion $y$ su variable independiente $x$  y su derivada $\frac{dy}{dx}$, por ejemplo $\left(y^2+xy^2\right)\frac{dy}{dx}+x^2-x^2y=0$. Si se despeja $\frac{dy}{dx}$ de $F\left(x,y,\frac{dy}{dx}\right)=0$ obtenemos $\frac{dy}{dx}=g(x,y)$.


## Ecuaciones diferenciales de variable separable

Si una ecuación ordinaria de primer orden y primer grado $\frac{dy}{dx}=f(x,y)$ se puede expresarse como $M(x)dx+N(y)dy=0$ entonces la ecuación recibe el nombre de ecuación diferencial ordinaria de variable separable y la solución es por integración directa $$\int M(x)dx+\int N(y)dy=0$$


```{exercise}
$\left(y^2+xy^2\right)\frac{dy}{dx}+x^2-x^2y=0$
```

```{solution}
\begin{align*}
0&=y^2\left(1+x\right)dy+x^2\left(1-y\right)dx\\
&=\frac{y^2}{1-y}dy+\frac{x^2}{1+x}dx
\end{align*}

integrando se tiene $$\int\frac{y^2}{1-y}dy+\int\frac{x^2}{1+x}dx=\int 0$$
$$(x+y)(x-y-2)+2\ln\left\vert\frac{1+x}{1-y}\right\vert=k$$
```


```{exercise}
$\left(y^2+xy^2\right)\frac{dy}{dx}+x^2-x^2y=0$
```

```{solution}
\begin{align*}
0&=y^2\left(1+x\right)dy+x^2\left(1-y\right)dx\\
&=\frac{y^2}{1-y}dy+\frac{x^2}{1+x}dx
\end{align*}

integrando se tiene $$\int\frac{y^2}{1-y}dy+\int\frac{x^2}{1+x}dx=\int 0$$
$$(x+y)(x-y-2)+2\ln\left\vert\frac{1+x}{1-y}\right\vert=k$$
```

## Ecuaciones diferenciales reducible a variable separable
Ecuaciones de la forma
\begin{equation}
\frac{dy}{dx}=f(ax+by+c)(\#eq:er1)
\end{equation}
donde $ax+by+c$ es la ecuacion de una recta sobre el plano euclideo son reducibles a variables separables. Si se realiza la sustitución de la derivada de $z=ax+by+c$ en la ecuación \@ref(eq:er1) se obtiene una ecuación de variable separable. En efecto de $z=ax+by+c$ se tiene $\frac{dy}{dx}=\frac{1}{b}\left(\frac{dz}{dx}-a\right)$ esto en \@ref(eq:er1) genera $\frac{1}{b}\left(\frac{dy}{dx}-a\right)=f(z)$ que es una ecuacion de variable separable $$\frac{dy}{a+bf(z)}=dx.$$



## Ecuaciones diferenciales homogéneas
```{definition}
Una función $f(x,y)$ es **homogenea** de **grado** $k$ si verifica $$f\left(\lambda x, \lambda y\right)=\lambda^kf(x,y)$$
```

```{}

```

## Ecuaciones diferenciales reducible a homogéneas

## Ecuaciones diferenciales exactas

## Ecuaciones diefrenciales lineales de primer orden

## Ecuaciones diefrenciales de Bernoulli
Son de la forma
\begin{equation}
\frac{dy}{dx}+p(x)y+q(x)y^{2}=f(x)
(\#eq:w1w)
\end{equation}

La ecuación se resuelve si solo se conoce una solución particular \(y_{1}(x)\). Conocida dicha solución, se hace el cambio
\begin{equation}
y(x)=z(x)+y_{1}(x)
(\#eq:w2)
\end{equation}
despejando \( \frac{dy}{dx}\) en la Ecuación \@ref(eq:w1w) y comparando con la derivada de la Ecuación \@ref(eq:w2), se obtiene 
\[\frac{dy}{dx}=-p(x)y-q(x)y^{2}+f(x)=\frac {dz(x)}{dx}+\frac {dy_{1}}{dx}
\]
además ya que \(y_1\) es solución de Ecuación \@ref(eq:w1)  es decir:
\begin{align}
-p(x)y-q(x)y^{2}+f(x)&=\frac {dz}{dx}-p(x)y_{1}(x)-q(x)y_{1}(x)^{2}+f(x)\notag\\
\frac{dz}{dx}&=p(x)(y_{1}-y)+q(x)(y_{1}^{2}-y^{2})(\#eq:w3)
\end{align}
la Ecuación \@ref(eq:w2) genera \(y_1-y=-z\) y \(y_1^2-y^2=z^2+2y_1z\) lo cual al sustituirlos en la Ecuación \@ref(eq:w3) resulta
\begin{align*}
\frac{dz}{dx}&=-p(x)z-q(x) \left(z^{2}+2zy_{1}\right)\\
&=-\left(p(x)+2q(x)y_{1}(x)\right)z-q(x)z^{2}
\end{align*}
que corresponde a una ecuación diferencial de Bernoulli.

```{remark}
Obsérvese que si se hace la sustitución:
\[y(x)=y_{1}(x)+{\frac {1}{z(x)}}\]
propuesta por Euler en la década de 1760 esto lleva directamente a una ecuación lineal diferencial de primer orden.
```



## Ecuaciones diferenciales de Riccati


## Ecuaciones diferenciales de Lagrange y Clairouts


## Ecuaciones diferenciales no resueltas con respecto a la primera derivada


```{exercise}
Sean los datos 
```

```{solution}
Entonces
  
```




